---

- name: cisco Router Health Check
  hosts: Cisco_Azure

  tasks:
    # Check the IOS Device Configuration
    - name: Cisco Device Config
      ios_facts:
        gather_subset: all

    - debug:
        msg:
          - "The Hostname is {{ ansible_net_hostname }}"
          - "The Device Name is {{ ansible_net_model }}"
          - "The Serial Number is {{ ansible_net_serialnum }}"
          - "The OS version is {{ ansible_net_version }}" 

    # check the cpu usage on the router
    - name: cisco check cpu usage
      ios_command:
        commands:
          -  show processes cpu
      register: sh_outputs

    - debug:
        msg: "{{ sh_outputs['stdout_lines'] }}"
    
    # check the memory usage on the router
    - name: Get the Memory Usage
      ios_command:
        commands:
          - show platform software status control-processor brief
      register: memory_usage
    
    - debug:
        msg: "{{ memory_usage['stdout_lines'] }}"

    # check the license status
    - name: Get the IOS License Status
      ios_command:
        commands:
          - show license udi
      register: license_status

    - debug:
        msg: "{{ license_status['stdout_lines'] }}"

    # check the Device Interface
    - name: get the IOS Device Interface
      ios_command:
        commands:
          - show int
      register: interface

    - debug:
        msg: "{{ interface['stdout_lines'] }}"
