---

- name: regex
  gather_facts: no
  hosts: Cisco_Azure


  tasks:
    - name: Test Rexeg cisco uptime
      ios_command:
        commands:
          - show version
        wait_for: result[0] contains uptime is
      register: wait_result
   
    - debug:
        msg: 
          - "{{ wait_result['stdout_lines'] | regex_findall('\\S+ uptime is [\\d+] [a-zA-Z]+, [\\d]+ [a-zA-Z]+') }}"
          - "{{ wait_result['stdout_lines'] | regex_findall('Uptime [*a-zA-Z \\d,]+') }}"
